### ISSUE TITLE
2 small South African clusters of Omicron/Delta recombinants with interesting Spike mutations (8 sequences)

### ISSUE THREAD

**Issue by JosieLikesCats** [cov-lineages/pango-designation#844] opened 2022-07-14 18:44 UTC
Hi everyone, I'm just opening this issue to highlight that there are several sequences with an unusual mutation pattern in our most recent upload from South Africa, which will potentially represent two new lineages if more sequences are detected. The teams in our genomic surveillance network (NGS-SA) as well as our public health institute (NICD) are closely monitoring the sequences and cases in the country. These new constellations have been detected only in a small proportion of recent data, and our cases remain low.
 
I know these do not yet meet requirements for designation, as there are only N=4 and N=3 (2 available on GISAID, last 1 will be released tomorrow) sequences for each constellation, but we thought they would probably be of interest and picked up here/on Twitter eventually. For now, please see below for some details and the major mutation profiles for the two groups of sequences. 

**N=4 constellation 1**
Earliest sequence: 28 June 2022
Most recent sequence: 29 June 2022
Circulating: Gauteng, South Africa
Nextclade assigns 21M but flags lots of private mutations (mainly 21J), pango assigns Unassigned/B.1.1.529

**Genomes**
EPI_ISL_13830378
EPI_ISL_13830377
EPI_ISL_13830376
EPI_ISL_13830375

**N=3 constellation 2**
Earliest sequence: 13 June 2022
Most recent sequence: 24 June 2022
Circulating: Limpopo, South Africa
Nextclade assigns 21J but flags lots of private mutations (mainly 21K/21L), pango assigns XD

**Genomes**
EPI_ISL_13830379
EPI_ISL_13830380

**Evidence**
[constellation1_defining_aa_changes.xlsx](https://github.com/cov-lineages/pango-designation/files/9114376/constellation1_defining_aa_changes.xlsx)
[constellation2_defining_aa_changes.xlsx](https://github.com/cov-lineages/pango-designation/files/9114377/constellation2_defining_aa_changes.xlsx)

Spike mutations in constellation 1 only, relative to Omicron: R21G, F486P, P621S, A706V
Spike mutations in constellation 2 only, relative to Omicron: S477D
Shared mutations relative to Omicron BA.4/5: L18F, T19R, W152L, E156del, F157del, R158G, F186L, G446D, T1117I
Notably both clusters have a second silent nt change in L452R not present in BA.4/5.
There are some significant differences outside spike (see attached mutation profiles).
The sites 213, 371, 373, 375, 376, 408, and 764 are not reliably covered by the data, so they cannot be confirmed yet.
UShER tree (including 7th sequence to be uploaded): https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1ef08_5f410.json (in a previous Usher tree they clustered near XD).

**Comment by FedeGueli** [comment] 2022-07-14 18:57
Thx very important issue. a lot of Delta mutation too.

@corneliusroemer @AngieHinrichs @rambaut @chrisruis @InfrPopGen @thomaspeacock @theosanderson please take a look. Urgent.

**Comment by corneliusroemer** [comment] 2022-07-14 19:05
Thanks @JosieLikesCats for flagging these at such an early stage, they are indeed very interesting sequences.

I'm sorry, I can't really provide much insights yet, but I would very much appreciate if you could try to answer some questions that come to mind:
Do you happen to have raw reads for these - this would be very helpful to validate that the sequences are real and not for example due to coinfection. Are there other possible explanations for these? Do you know how closely related the individuals are who were sequenced? 

Where in Limpopo and Gauteng are these from? Google maps says ~400km but could the Limpopo ones also be from a place closer to Gauteng province?

These sequences should be run through sc2rf to check for recombination - first impression is that it's very recombinanty. But also that both sequences seem to have some things in common. Very speculatively, these could represent different results of intra host recombination - but one needs to look at this in more detail.

It may be worth splitting this issue up and separate the proposals but for now to keep things simple I think it's fine to keep them both together.

Here are screenshots from Nextclade to save everyone some time:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25161793/179063201-d1ed3e43-dc7b-4567-a716-e355dc23c1c0.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25161793/179063223-e6fd6d17-5eac-4983-bb1a-2d6f2099ddb2.png">

**Comment by silcn** [comment] 2022-07-14 19:44
Just spotted these too, went to check and found this issue. These look like some weird combination of three different lineages: AY.45, a divergent BA.4/5, and BA.2 (seen near the 3' end where BA.4/5 mutations are absent from the Omicron-derived sections). Both have lots of apparent breakpoints but the 3' end of constellation 2 is particularly messy and seems to switch back and forth almost every mutation - the N protein alone goes Omicron/Delta/Omicron/Delta.

If these are real I wouldn't be surprised if they are new emergences from the Omicron source, especially given the location.

**Comment by JosetteSchoenma** [comment] 2022-07-14 21:14
Hi, I have run them through Sc2rf. It looks mostly like a Delta/BA.5 recombinant to me. But with several breaking points and 11 shared private mutations between the 2 clusters. 
The graph on the bottom is best. Green being BA.2 and red being Delta mutations. It starts with some example BA.4 and BA.5 samples. I included the first graph, where I selected the BA.1 and BA.2 clade, because it shows 6 South-African samples, where the bottom one somehow loses 2 and shows just 4.
![image](https://user-images.githubusercontent.com/94831035/179087099-5f2ca1f1-a23b-4c4a-80ca-18e091685356.png)

**Comment by corneliusroemer** [comment] 2022-07-14 21:33
The small cluster (no 2) very much looks like a 21J and BA.4/5 recombinant to me - but with an unusually high number of 5 breakpoints. The ranges are as follows:

```
0-2790: BA.4/5 [length ~ 3-4k]
2791-4180: BA.4/5 -> 21J (BP1)
4181-21846: 21J [length 18-19k]
21847-21986: 21J -> BA.2 (BP2)
21987-24912: BA.4/5 [length 3k]
24913-24999: BA.4/5 -> 21J (BP3)
25000-28310: 21J [length 3-4k]
28271-28880: 21J -> BA.2 (BP4)
28881-28916: BA.4/5 [length 40-1.2k]
28917-29401: BA.4/5 -> 21J (BP5)
29402-end     : 21J [length 500-1k]
```

**Comment by JosetteSchoenma** [comment] 2022-07-14 22:16
Here is the Usher tree:
![Screenshot_20220715-001558_Twitter.jpg](https://user-images.githubusercontent.com/94831035/179097778-ef067591-0159-41bc-a28e-0ea38690d78c.jpg)

**Comment by silcn** [comment] 2022-07-14 22:35
Here is a spreadsheet comparing the mutations to AY.45, BA.2, BA.4 and BA.5: [pango844.xlsx](https://github.com/cov-lineages/pango-designation/files/9115923/pango844.xlsx)

Constellation 1 has at least 6 breakpoints; constellation 2 has at least 5 as @corneliusroemer says. Could potentially be even more, as there are a couple of places where a single mutation or reversion could have been gained convergently or through recombination.

I'm also unconvinced that BA.4/5 are involved - I think the Omicron parent may just be a divergent BA.2. Looking at all of the locations where BA.2 and BA.5 differ, referring to the constellations as C1 and C2 for short:
12160: C1 looks like BA.2, C2 is Delta
21765-21770 (S:69/70): both Delta
22917 (S:452): both look like BA.5
23018 (S:486): both Omicron-derived here, but nucleotide is different from BA.2 and BA.5
23040 (S:493): both look like BA.5
26529 (M:3): both Delta
26858, 27259, 27382-4: C1 could be Delta or BA.5, C2 is Delta
27889: C1 looks like BA.2, C2 is Delta

If BA.5 is involved and not BA.2, we have to believe that the silent mutations at 12160 and 27889 both reverted. In my humble opinion, this seems much less likely than S:L452R and S:R493Q arising independently on top of BA.2 - after all, we've seen that in BA.2.77 too.

The evidence against BA.4 is even stronger, e.g. neither constellation has the deletion in nsp1.

**Comment by AngieHinrichs** [comment] 2022-07-14 22:54
Thanks @JosetteSchoenma -- here is a link to the UShER view with a permanently saved .json file that won't be deleted in a couple days, and with branches labeled by reversions/back-mutations:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/pango-designation-844.json?branchLabel=back-mutations&c=pango_lineage_usher&label=nuc%20mutations:T19955C

Since this is apparently a recombinant, UShER is not as useful as it might be otherwise.  The phylogenetic tree assumes a steady accumulation of mutations, but recombinants violate that assumption.  UShER places a recombinant sequence on the branch of the tree where it has the fewest differences from existing sequences, which usually corresponds to one of the parent lineages -- but there are reversions/back-mutations for the portions of the genome contributed by the other parent.  (In fact, a long branch with multiple reversions is the signal that our RIPPLES tool uses to look for potential recombinants in the big tree... we should run that again one of these days!)

These sequences are placed on a branch of BA.5 that is already riddled with various reversions that are probably mostly sequencing artifacts -- but the long branch makes it pretty clear that these sequences are different from the others, and that placement is just the best that usher could do given the circumstances, not necessarily an indication that the sequences on that subtree are closely related.

**Comment by Sinickle** [comment] 2022-07-14 23:58
I agree with Silcn's analysis and reasoning. 

One small thought to add - Regarding the silent mutation 22916A at S:452. 
If the Omicron contributor is BA.2, then that mutation would create S:L452M. Possibly this was an intermediate step, before gaining S:M452R.

**Comment by UnusualTimes** [comment] 2022-07-15 08:31
Could this be an XT (or similar) + BA.5 recombination ?

**Comment by FedeGueli** [comment] 2022-07-15 09:46
Possible CvSp query to catch both the constellation:

https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=M%3A146H&nucMutations=8595T%2C15026T&


based on the great list by @silcn

**Comment by JosieLikesCats** [comment] 2022-07-15 12:40
Thanks for all analysis so far, very interesting to read all the comments! The final sequence has been uploaded to GISAID, so it should be available soon - I'll edit this comment once it's released.

@corneliusroemer to answer some of your questions:
I'm currently analysing the raw data more closely, and will update the sequences if any of the sites turn out to be incorrect/poorly supported. I've also got some other people helping me look at them, and we can potentially share the read counts per site etc. once we're done. We do currently have the samples in the pipeline to be resequenced to confirm some of the sites as well.

The sequences are from Johannesburg (Gauteng) and Polokwane (Limpopo), which are two of the main cities in each province. We have also had school and university holidays recently, and so there has likely been increased travel between provinces. 

I see recombination is being looked at quite closely by everyone, so I'll just add that we have some NGS-SA team members also taking a look with a variety of tools; we'll update accordingly if we find anything interesting. 

Thanks for adding the screenshots! I had considered two separate issues but thought for now since there are so few it made sense to keep it together. Happy to split these in future if needed.

**Comment by FedeGueli** [comment] 2022-07-18 14:44
I can confirm this query catches 7 out of 7 sequences of this new variant:
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?aaMutations=M%3A146H&nucMutations=8595T%2C15026T&

**Comment by ryhisner** [comment] 2022-07-19 18:36
There's a new sequence uploaded today clearly related to the others, though it's 29.7% NNN's. It's part of constellation 1, but spike residues 1-340 and 670-1044 are blank according to NextClade. Collection date 2022-7-4.

**Comment by ryhisner** [comment] 2022-07-19 18:41
There's a new sequence from Gauteng uploaded today clearly related to the others, though it's 29.7% NNN's—EPI_ISL_13913050


It has F486P and P621S, so it's part of constellation 1, but spike residues 1-340 and 670-1044 are blank according to NextClade. Collection date 2022-7-4.

Here's the Usher tree: https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_2267d_6f9c40.json?c=gt-S_621&label=nuc%20mutations:C7124T,C8595T,C8986T,G9053T,C15026T,G18163A,C21614T,C21618G,T21762C,G22017T,T22118C,G22899A,C22916A,T22917G,G23040A,C24912T,C25413T,G26959A,C27259A

**Comment by AngieHinrichs** [comment] 2022-07-19 18:54
@ryhisner thanks for adding the EPI_ISL ID there, was just about to ask, and sorry the UShER web interface is using an old fasta-reading library that truncates names at the space character... "hCoV-19/South" is a pretty useless label.

**Comment by AngieHinrichs** [comment] 2022-07-19 22:35
EPI_ISL_13913050 (SouthAfrica/CERI-KRISP-K045132/2022) is the first of these from outside NICD, and it is more similar to C1 than it looks in that UShER tree view -- it has Ns at 4456, 5869, 10198, 12163, 21623, and 23679, and it has C10954T and C28531T like NICD-N47701 and NICD-N47705, so I would expect UShER to place it at the end of that branch, instead of splitting it in the middle.  Looking into why it didn't.

Meanwhile here's a sc2rf view so you can see how CERI-KRISP-K045132 looks pretty much like the NICD C1 sequences, but with more Ns, and without reversions at 22686, 22688 and 22786 (common casualties of amplicon dropout I think):

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/186983/179857803-e6340bc3-b934-4a7b-b0ab-cff13466303c.png">

**Comment by thomasppeacock** [comment] 2022-07-24 13:11
Although these clusters don't fulfill the minimum number of sequences - I think the extremely unique potential pattern of recombination might mean if sequences keep appearing they should get assigned as there will be justification for being able to refer to them by a non-ambiguous designation. Going to put a monitoring tag on this for now (hope thats okay @chrisruis @InfrPopGen !).

**Comment by corneliusroemer** [comment] 2022-07-24 14:44
Agree that it's worth seeing if any new sequences in this cluster appear and if they do to designate.

The minimum number of sequences is not a hard limit, we can make exceptions if there are good reasons (there are here).

**Comment by JosieLikesCats** [comment] 2022-07-28 19:34
Hi everyone, just a heads-up that one more sequence from constellation 2 will be released in the next couple of hours (N46078, will update once I have the EPI ISL as well). Also from Limpopo, with collection date of 30 May. We haven't yet detected any more recent samples but are monitoring closely.

**Comment by silcn** [comment] 2022-07-29 13:51
The new constellation 2 sequence is missing M:R146H and so will not be picked up by @FedeGueli's cov-spectrum query. Here is a query that will pick up everything once cov-spectrum is updated with the new sequence:
[https://cov-spectrum.org/explore/South%20Africa/AllSamples/AllTimes/variants?variantQuery=%5B5-of%3A+8595T%2C+15026T%2C+21614T%2C+22118C%2C+22899A%2C+22916A%2C+24912T%2C+26959A%5D&](https://cov-spectrum.org/explore/South%20Africa/AllSamples/AllTimes/variants?variantQuery=%5B5-of%3A+8595T%2C+15026T%2C+21614T%2C+22118C%2C+22899A%2C+22916A%2C+24912T%2C+26959A%5D&)

**Comment by FedeGueli** [comment] 2022-08-02 14:42
thx @silcn checked your new query 9 out of 9!
well done.
https://cov-spectrum.org/explore/South%20Africa/AllSamples/AllTimes/variants?variantQuery=%5B5-of%3A+8595T%2C+15026T%2C+21614T%2C+22118C%2C+22899A%2C+22916A%2C+24912T%2C+26959A%5D&

**Comment by silcn** [comment] 2022-08-23 12:21
2 more sequences from Constellation 1: EPI_ISL_14585888, EPI_ISL_14585891
Both from Western Cape, South Africa, sampled 2022-08-08.

**Comment by corneliusroemer** [comment] 2022-08-24 15:51
Here's the Usher tree with the two new sequences - I think it'd be worth designating the bigger cluster of the two as it seems to continue circulating and has a very intriguing spike profile.
<img width="2263" alt="image" src="https://user-images.githubusercontent.com/25161793/186464177-121a8321-7f37-42b5-8f10-3b4e2e95980b.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_17d5d_648160.json?c=Nextstrain_clade_usher&label=nuc%20mutations:C12747T,C12880T,T23018C,T23019C,C23423T,C26681T,C27575G,A29510C

**Comment by aq-sun** [comment] 2022-08-25 16:57
Thanks for submitting, we've designated this recombinant lineage as XAY with 11 new designations.

**Comment by corneliusroemer** [comment] 2022-08-25 17:03
@aq-sun can you confirm whether you designated one or both lineages? The proposal was for two separate clusters - did you merge them into one or designate only one of the two? If only one was merged we should probably keep the issue open for the other cluster?

**Comment by silcn** [comment] 2022-08-25 17:23
Looks like XAY encompasses both clusters. Possibly not strictly following the Pango rules, but there clearly is shared ancestry between the two clusters even if it's impossible to say what the "common ancestor" is. In my opinion the larger cluster should immediately be designated XAY.1, and if the smaller cluster reaches 5 sequences then it should be XAY.2.

**Comment by aq-sun** [comment] 2022-08-26 11:16
This seems like the appropriate thing to do - I'll reopen the issue and monitor for further development in constellation 2, and designate the larger constellation as XAY.1.

**Comment by corneliusroemer** [comment] 2022-08-26 11:22
Great! I wouldn't make these sublineages of each other as there may be
recombination involved. I'd just call this XAV, and the next one XAW or
whatever :)

**Comment by aq-sun** [comment] 2022-08-26 11:26
I'll leave the first cluster as XAY then!

**Comment by FedeGueli** [comment] 2022-08-30 16:53
One more sequence i think popped up:

EPI_ISL_14728611

**Comment by aq-sun** [comment] 2022-08-31 11:23
Added this to XAY.

**Comment by FedeGueli** [comment] 2022-09-06 09:37
Gisaid query  M_R146H, Spike_F186L for XAY

**Comment by AngieHinrichs** [comment] 2022-09-06 18:50
> Gisaid query M_R146H, Spike_F186L for XAY

@FedeGueli I think that query covers both C1 (designated XAY) and C2 (monitored).

Extending your query for XAY: `M_R146H, Spike_F186L, Spike_F486P`

for C2: `M_R146H, Spike_F186L, N_D63G`

**Comment by FedeGueli** [comment] 2022-09-06 21:32
Thx @AngieHinrichs !! yes i usually do the S:F486P and then the other! good to have them separately thank you very much

**Closed** 2022-09-14 15:43 UTC
Labels: monitor, designated, recombinant

**Comment by FedeGueli** [comment] 2022-09-15 17:34
New XAY just uploaded an elderly man in Cape Town collected on 31/08/22.

EPI_ISL_14975893

**Comment by corneliusroemer** [comment] 2022-09-28 13:05
The first international XAY has just appeared in Denmark:

`hCoV-19/Denmark/DCGC-585187/2022|EPI_ISL_15155569|2022-09-23`

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/25161793/192785740-6a3a3800-85c6-4c0e-be67-996d7672332f.png">

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_16aa0_445360.json?c=pango_lineage_usher&label=nuc%20mutations:G15451A,C16466T,C19220T,A22688G,A22786C,T25584C,T26270C,G26577C,A26709G,T26767C,G29742T

**Comment by JosetteSchoenma** [comment] 2022-10-07 21:49
There is another XAY from Denmark. Getting the same place on the Usher tree as the one @corneliusroemer mentioned. 2nd of October 2022. EPI_ISL_15284246.

**Comment by FedeGueli** [comment] 2022-10-09 16:14
Two XAY more sequences from south africa have been uploaded collected on 29/8 and 14/9  both from Gauteng and baseline surveillance.
EPI_ISL_15259248, EPI_ISL_15259343

**Comment by FedeGueli** [comment] 2022-10-13 20:57
i think i have found a better query for XAY : Spike_P621S,Spike_F186L , it actually founds 27 sequences from 3 countries while Gisaid Pangolin calls 23 viruses XAY and our old manual query a lot less.

@AngieHinrichs

**Comment by AngieHinrichs** [comment] 2022-10-14 02:59
Thanks @FedeGueli, that helped me find a couple new CA sequences that were being excluded from the tree but should be added tomorrow!

https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/~angie/XAY.2022-10-13.json?branchLabel=Spike%20mutations&c=pango_lineage_usher&label=nuc%20mutations:G4184A,C4321T,G10447A,C12747T,C12880T,T23018C,T23019C,C23423T,C26681T,C27575G,A29510C,T29742G&s=hCoV-19/USA/CA-FG-296207/2022%7CEPI_ISL_15324975%7C2022-09-30,hCoV-19/USA/CA-FG-296179/2022%7CEPI_ISL_15324972%7C2022-09-30

Also missing but hopefully added tomorrow: SouthAfrica/SU-NHLS_5859/2022|EPI_ISL_14975893|2022-08-31

**Comment by FedeGueli** [comment] 2022-11-09 19:49
Found a sequence that NExtclade see as XBA but Usher puts outside everyhting starting from the B.1.1.529 root, bu it is mixed.

It is from Belgium and sampled recently: EPI_ISL_15537619

@corneliusroemer @thomasppeacock @AngieHinrichs @JosieLikesCats @JosetteSchoenma @c19850727 @silcn 

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_274cf_c03220.json?c=pango_lineage_usher&s=hCoV-19/Belgium/UZB_548202210266/2022%7CEPI_ISL_15537619.%7C2022-10-24

![Schermata 2022-11-09 alle 20 49 17](https://user-images.githubusercontent.com/87669813/200927122-7ddd6aaf-60bb-4f49-99b7-16e2e1d4b799.png)

**Comment by AngieHinrichs** [comment] 2022-11-09 20:32
Command-line nextclade places it with XBA as the closest match... but with 21 reversions relative to the XBA placement, as well as 7 mutations associated with other clades, and 28 additional mutations.  It's excluded from the UShER tree because it's Omicron-ish but so divergent from its nextclade placement.  My guess is contamination, but that's just my guess based on looking at nextclade numbers; someone looking at the raw data might see something else.

**Comment by oobb45729** [comment] 2022-11-09 21:20
It looks like another recombinant strain that is related to XAY/XBA to me. The reversions can be easily explained by different breakpoints. This one is an XBA-like with a Delta-like S2. The S2 part (P681R+T736I+T895N+D950N) looks pretty real. T895N is one of the most notable convergent mutations in the late Delta era.

**Comment by oobb45729** [comment] 2022-11-09 21:28
This one also may give some hints about how XAY/XBA evolved. This one has L452M, elaborating the L452M->R theory.

**Comment by oobb45729** [comment] 2022-11-10 01:07
A breaking point between S:EFR156G and S:V213G like XAY/XBA, which is also close to XAW and XBC breaking points.
Also like XAY/XBA/XBC, another breaking point somewhere in nsp1-nsp3 to get BA.2's orf1a:S135R.
And like XBA, a breaking point between N:D63G and N:R203K.
S:L18F+T19R+R21G like XAY and more intriguingly, Orf7a:T61S like XAY but with C27575G, not XAY's A27574T (both mutations are not common so far).
