### ISSUE TITLE
Sublineage of BA.5.2.24 (K444N) with S:S255F, S:N460K, E:V62F, ORF1a:V710I, ORF1a:G3578D (13 seq, 8 countries)

### ISSUE THREAD

**Issue by ryhisner** [cov-lineages/pango-designation#1214] opened 2022-10-13 01:06 UTC
### **Description**
**Sub-lineage of:** BA.5.2.24
**Earliest sequence:** 2022-9-17, Germany, Baden-Wurttemberg — EPI_ISL_15264132
**Most recent sequence:** 2022-10-5, Denmark, Hovedstaden — EPI_ISL_15316959
**Countries circulating:** Austria (3), Denmark (3), Spain (2), Canada (1), England (1), France (1), Germany (1), USA (1)
**Number of Sequences:** 13
**GISAID Query:** Spike_K444N, Spike_N460K, Spike_S255F, E_V62F
**CovSpectrum Query:** Nextcladepangolineage:BA.5.2.24* & S:N460K & S:S255F & E:V62F
**Substitutions on top of BA.5.2.24:**
**Spike:** S255F, N460K
**E:** V62F
**ORF1a:** V710I, G3578D
**Nucleotide:** G2393A, C8389T, G10998A, C13423T, G26428T, C22326T, T22942G

**USHER Tree**
https://nextstrain.org/fetch/raw.githubusercontent.com/ryhisner/jsons/main/BA.5.2.24%2BS255F%2BN460K%2BEV62F%2Betc.subtreeAuspice1_genome_19efb_757430.json

<img width="1500" alt="image" src="https://user-images.githubusercontent.com/33738461/195475460-622d7061-e071-4d6d-81cb-8a78e6ab852c.png">

**Evidence**
The S:N460K + S:K444X combination is a pretty known quantity at this point, and I believe this is the first lineage  measurable size with both that also has S:S255F. The impressive growth of BA.5.2.23 (which has S:Y145H, S:S255F, and S:V445A) despite no S:R346X or S:K444X mutation suggests that S:S255F may be of significant benefit in a BA.5.2 context. 

The first sequence was only collected on September 17, and it’s already been found in eight countries, so growth seems fast. It’s too early to say anything with confidence though, so we’ll have to see what this lineage dose in the next week or two before we’ll know if it has any staying power. 

**Genomes**
<details>
<summary>Genomes</summary>
EPI_ISL_15208607, EPI_ISL_15252615, EPI_ISL_15264132, EPI_ISL_15283290, EPI_ISL_15284350, EPI_ISL_15291085, EPI_ISL_15291093, EPI_ISL_15299647, EPI_ISL_15316756,
EPI_ISL_15316959, EPI_ISL_15321503, EPI_ISL_15329269, EPI_ISL_15337866
</details>

**Comment by Mydtlwn** [comment] 2022-10-13 01:35
Why do I look so familiar? Have   already mentioned it?

**Comment by Mydtlwn** [comment] 2022-10-13 01:37
#1190

**Comment by Mydtlwn** [comment] 2022-10-13 01:38
Are these two the same?

**Comment by corneliusroemer** [comment] 2022-10-13 03:06
Yep, duplicate of #1190, thanks for noticing @Mydtlwn

**Closed by corneliusroemer** 2022-10-13 03:06 UTC

**Comment by ryhisner** [comment] 2022-10-13 17:37
Man, I must've looked through half a dozen different proposals with N460K and K444N—even a different one with E:V62F!—and I still didn't catch #1190. Man, it's getting hard to even figure out if something has been proposed before with all this convergence. Thanks for catching this @Mydtlwn. I should've known @FedeGueli would never let a K444N + N460K lineage with more than five sequences slip through his fingers!

**Comment by Mydtlwn** [comment] 2022-10-14 10:39
I think it might be a good idea to use a file as a directory of posts!

**Comment by FedeGueli** [comment] 2022-10-15 00:10
Thx Ryan! better two than none! Sorry i didnt notice it before so i could have save you some time!
