### ISSUE TITLE
There are some mistakes here.

### ISSUE THREAD

**Issue by Kevin050308** [cov-lineages/pango-designation#2047] opened 2023-06-10 15:30 UTC
![image](https://github.com/cov-lineages/pango-designation/assets/121531357/9cfc1cbb-b6b1-4694-8f50-83aacd52a722)![image](https://github.com/cov-lineages/pango-designation/assets/121531357/7d5083ff-05d0-448f-a158-fe4c53c2bb25)![image](https://github.com/cov-lineages/pango-designation/assets/121531357/23071f6e-287e-453b-a06e-02e17659731f)![image](https://github.com/cov-lineages/pango-designation/assets/121531357/9965cf84-d6fd-4c49-8a8e-04a4d3cfd67c) 
My English is not very good, so please look at these pictures.

**Comment by Kevin050308** [comment] 2023-06-10 15:32
![image](https://github.com/cov-lineages/pango-designation/assets/121531357/2e83724c-95b9-4885-8996-4bfde6568007)

**Comment by Kevin050308** [comment] 2023-06-10 15:33
![image](https://github.com/cov-lineages/pango-designation/assets/121531357/a2739b52-d530-46ec-bda2-c8e984dcb9e3)

**Comment by Kevin050308** [comment] 2023-06-10 15:36
@corneliusroemer

**Comment by FedeGueli** [comment] 2023-06-10 15:36
@corneliusroemer @AngieHinrichs @InfrPopGen

**Comment by Mydtlwn** [comment] 2023-06-10 16:36
I noticed the exception at first, but I didn't find it when I checked the alias_key.json file, but I didn't check the lineage_notes.txt file later, but according to alias_key.json, it should GP.1

**Comment by corneliusroemer** [comment] 2023-06-10 17:23
Thanks @Kevin050308, you can also submit a PR in the future fixing the errors, if you figure out what the issue is.

Should be fixed now.

**Closed** 2023-06-10 17:22 UTC
