### ISSUE TITLE
New lineage proposal for Nextstrain clade 20A/Spike: F888L, E484K

### ISSUE THREAD

**Issue by erikalmecdc** [cov-lineages/pango-designation#8] opened 2021-02-12 08:29 UTC
by Erik Alm

Spike A67V, Spike D614G, Spike E484K, Spike F888L, Spike 69-70del, Spike Q52R, Spike Q677H, Spike 144del
Sub-lineage of: B.1
Earliest sequence: 2020-12-15
Most recent sequence: 2021-02-01
Countries circulating: Denmark, UK, USA, Spain, South Africa, Nigeria, France, Belgium, Canada, Australia, Jordan, Italy, Japan

A new variant of interest reported to ECDC by Denmark. Wide geographic circulation and carrying E484K. Rapid increase in Denmark recently.

Genomes

Evidence
![B1 lineage](https://user-images.githubusercontent.com/36880285/107745512-b8ac3880-6d14-11eb-816c-8f24befc337c.png)
[new lineage within B.1.xlsx](https://github.com/cov-lineages/pango-designation/files/5970483/new.lineage.within.B.1.xlsx)

Proposed lineage name

**Comment by rambaut** [comment] 2021-02-12 09:28
This is a duplicate of Issue #4 which has been assigned lineage `B.1.525` and has been pushed to the latest Pangolin release. Closing as duplicate but thanks for the submission, Erik.

**Closed by rambaut** 2021-02-12 09:28 UTC
Labels: duplicate
