### ISSUE TITLE
Several Lineages with Frameshift mutation in ORF7

### ISSUE THREAD

**Issue by Lukas67** [cov-lineages/pango-designation#1014] opened 2022-09-01 09:54 UTC
Dear all,

in our last sequencing runs we found several samples with the in the title mentioned frameshift.

The frameshift occurs, because of a deletion of a single or more nucleotides in the region around 27553 (ORF7a)

Compared to other sequences on gisaid, this framshift occurs on 1300 sequences across lineages (AY.25; AY.4; BA.1.1.; BA.2), sequence technologies (Illumina, Nanopore, PacBio) and assembly strategies (CLC genomics, Dragen, wf-Artic).

Example sequences:
EPI_ISL_9838895; EPI_ISL_13755209; EPI_ISL_14558255; EPI_ISL_9038765; EPI_ISL_9458360

What is the cause of this phenomenon?

Thanks and BR
Lukas

**Comment by corneliusroemer** [comment] 2022-09-01 11:15
There are a large number of known frameshifts that occur and seem to be tolerated at least for a while.

The cause is a frameshifting deletion. Why deletions happen in particular places is hard to say though it may be related to RNA secondary structure.

These are tolerated because ORF7a does not seem to be an "accessory" gene that is not totally necessary to survive.

I'll close this as it's not a lineage proposal and hence off topic.

**Closed by corneliusroemer** 2022-09-01 11:15 UTC
