### ISSUE TITLE
New proposed sub-lineage in India under B.1

### ISSUE THREAD

**Issue by banijolly** [cov-lineages/pango-designation#42] opened 2021-04-06 08:10 UTC
**Description**

Sub-lineage of: B.1
Earliest sequence: 2020-10-02 (EPI_ISL_1415203)
Most recent sequence: 2021-03-31 (EPI_ISL_1471955)
Countries circulating: India and Australia, Canada, Germany, Guadeloupe, New Zealand, Singapore, Sweden, USA, United Kingdom

Lineage was found to be circulating in India in 2021, predominantly in the states of Maharashtra, along with other states Gujarat, West Bengal, Karnataka, Kerala and Tamil Nadu (https://www.bbc.com/news/world-asia-india-56517495). The genomes have a combination of 2 mutations in the spike protein: L452R and E484Q. 

**Genomes**
[gisaid_accessions.txt](https://github.com/cov-lineages/pango-designation/files/6262889/gisaid_accessions.txt)

**Evidence**
![image](https://user-images.githubusercontent.com/47384613/113679464-67e60a00-96dd-11eb-875e-c3911084fa67.png)
 Live nextstrain instance is available at https://nextstrain.org/community/banijolly/Phylovis/COVID-India?c=gt-S_452,484

**Comment by aineniamh** [comment] 2021-04-06 08:47
Hi @banijolly, I think this issue is a duplicate of #38, which has been designated as B.1.617. 

I'll close this issue now but thanks for posting!

**Closed by aineniamh** 2021-04-06 08:47 UTC
Labels: designated, duplicate

**Comment by banijolly** [comment] 2021-04-06 09:53
Yes indeed it has been already designated in issue #38, sorry for not noticing this before.

Thanks a lot, @aineniamh for pointing this out!
