### ISSUE TITLE
Saltation/chronic BA.2.12.1 in US-CT with 14 new Spike mutations [2 seqs from 2022-12-29]

### ISSUE THREAD

**Issue by corneliusroemer** [cov-lineages/pango-designation#1624] opened 2023-02-06 20:35 UTC
Came across a quite heavily mutated saltation BA.2.12.1 with 14 S amino acid mutations (looked at 453F sequences)

It's probably not a recombinant, there are no reversions or mutations characteristic of another clade.

EPI_ISL_16757210
EPI_ISL_16818660

Both sequences were collected on the 29th of December 2022 in the US state of Connecticut. Sequence submission on 2nd/3rd of February. Usher has not found neighbours.

<img width="2329" alt="image" src="https://user-images.githubusercontent.com/25161793/217078325-f93728e9-485d-4881-a3d7-7218688c30e1.png">

<img width="762" alt="image" src="https://user-images.githubusercontent.com/25161793/217078334-0f510da7-b99d-4b18-9b5a-fc54120bf6c7.png">

<img width="2084" alt="image" src="https://user-images.githubusercontent.com/25161793/217078342-f7f08d6c-1b75-4c67-b366-9fc499758a11.png">
https://next.nextstrain.org/fetch/genome-test.gi.ucsc.edu/trash/ct/subtreeAuspice1_genome_test_5ff11_162160.json?branchLabel=Spike%20mutations

According to Bloom lab calculator it's got high ACE2 binding (+1.3) (despite not having the 493 reversion common in all second generation BA.2) and modest immune escape (+0.3). It notably lacks 346T and 460K, but has 453F instead and 417T.

I'm not sure if the sequences are from the same patient, the metadata indicates different submitting/originating labs.

One strain name has an unusual `a` suffix.

Not worth a designation at this point as there's lack of evidence of spread but it's a curious pair of sequences.

**Comment by cvejris** [comment] 2023-02-06 22:36
Very interesting mutational profile - almost all S1 changes are at convergent sites and there are three 2-nucleotide mutations (339Y, 376S, 417T)

**Comment by FedeGueli** [comment] 2023-02-06 23:35
Thx Cornelius . i have to add that @ryhisner spotted it and it was subsequently tracked in our growth advantages sheet privately

**Comment by MCB6** [comment] 2023-02-06 23:43
About the -a suffix, nearly a half of DPH's uploads have it. Most of them are XBB.1.5, typical for this area, but for example EPI_ISL_16818670
 is a lone DF.1.1 genome, not a duplicate of some other lab's submission. So I'd say that their BA.2.12.1 shouldn't be a mere duplicate of something processed elsewhere...

**Comment by InfrPopGen** [comment] 2023-04-07 10:26
It looks like this did not spread, or it was not detected. Consequently, I think it can be closed for now.

**Closed by InfrPopGen** 2023-04-07 10:26 UTC
Labels: monitor, BA.2, Saltation
