### ISSUE TITLE
BA.5.2.48 sublineage with N:Q241K   circulating in China 2223 sequences as 16/02/23

### ISSUE THREAD

**Issue by FedeGueli** [cov-lineages/pango-designation#1478] opened 2022-12-27 15:20 UTC
This lineage was spotted first by Yunlong Richard Cao, 

Defining mutations :  
BA.5.2 ( > C27513T > C27012T > G12310A > C16616A (Orf1b:1050N)) 
then C2710T > C8626T > C11824T > T17208C > N:Q241K (C28994A )

Tree:
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice2_genome_1acf9_b0ad20.json?c=userOrOld&label=id:node_7080113
<img width="1132" alt="Schermata 2022-12-27 alle 16 18 08" src="https://user-images.githubusercontent.com/87669813/209686543-23c405f2-70db-4329-b302-8170c15ee1e5.png">

Gisaid Query: N_Q241K,NSP13_T127N,M_D3N

Sequences : 18

EPI_ISL_16259462, EPI_ISL_16259469, EPI_ISL_16259474,
EPI_ISL_16259481, EPI_ISL_16259506, EPI_ISL_16283958,
EPI_ISL_16283962, EPI_ISL_16283966, EPI_ISL_16283969,
EPI_ISL_16283971, EPI_ISL_16283985-16283987, EPI_ISL_16283993,
EPI_ISL_16284002-16284003, EPI_ISL_16284007, EPI_ISL_16286992,

**Comment by AnonymousUserUse** [comment] 2022-12-27 17:32
This lineage seems to be a sublineage of https://github.com/cov-lineages/pango-designation/issues/1471

**Comment by FedeGueli** [comment] 2022-12-27 18:40
> This lineage seems to be a sublineage of #1471

thx  for noticing i will wait for the decision of @corneliusroemer and @InfrPopGen if designate or not 1471 from T17208C.

**Comment by FedeGueli** [comment] 2022-12-27 20:24
30 sequences now, big upload from Singapore this evening

**Comment by FedeGueli** [comment] 2022-12-28 23:41
36 as today, its designation should be happen ONLY after a decision will be taken on #1471

**Comment by FedeGueli** [comment] 2023-01-02 00:11
this is the bigger sublineage of #1471 now at 71 sequences. It should be designated just after the parent.

**Comment by FedeGueli** [comment] 2023-01-06 20:02
This is the biggest sublineage of the recently designated BA.5.2.48 sublineage dominating in China, accounting for nearly half of the seqeunces assigned to the parental lineage.

@InfrPopGen @thomasppeacock @corneliusroemer

**Comment by aviczhl2** [comment] 2023-01-09 02:43
175 now, Italy and New Zealand. 

Italy EPI_ISL_16431224.  EPI_ISL_16431225
New Zealand EPI_ISL_16436171

Travel history unknown, are they locally transmitted?

**Comment by FedeGueli** [comment] 2023-01-21 21:30
With the  last upload from Shandong this represents around half of BA.5.2.48 sequences

**Comment by wending-lee** [comment] 2023-01-30 04:33
Confirmed in wastewater. This mutation has been detected most prevalent (77 out of 88 samples, detection threshold at >100 reads) in wastewater samples collected in the recent two months in southern China. 
We've been monitoring novel mutations that have not been assigned to any lineages, the most prevalent nuc mutations with >50% in wastewater samples are: C28994A(0.875), C5628T(0.864), A28370T(0.807), C16887T(0.727), G21987A(0.557), T26773C(0.534).

**Comment by FedeGueli** [comment] 2023-02-16 21:25
2233 seqs as today

**Comment by corneliusroemer** [comment] 2023-02-17 14:19
Yep, this is a clear one to designated. Will assign myself

**Closed** 2023-02-19 19:22 UTC
Labels: BA.5
