### ISSUE TITLE
BF.7 sublineage with S:C1243F circulating in China (292 seq as of 2023-01-06)

### ISSUE THREAD

**Issue by silcn** [cov-lineages/pango-designation#1470] opened 2022-12-26 04:03 UTC
Proposal for a sublineage of BF.7
Earliest seq: 2022-09-27 (Inner Mongolia, China)
Countries detected: China (15 seq, from Beijing and Inner Mongolia), Singapore (8, including 4 travellers from China), Cambodia (1), Italy (1)

Mutations on top of BF.7: 
ORF7a:H47Y, then ORF1b:L238F, then S:C1243F, ORF1a:V274L, C29632T

GISAID query: Spike_C1243F, NSP2_V94L + nuc mutation C29632T

We've got a Christmas present: actual sequences from China! Based on these, and samples from travellers arriving in Singapore and Japan, there appear to be two main lineages circulating in China, and this is one of them (the other is a BA.5.2+ORF1b:T1050N, see #1471). It was circulating in Inner Mongolia as early as late September, well before the abandonment of the zero-Covid policy, so its high prevalence in China is presumably due to a founder effect; however, the selection pressure from immune escape is much lower in China than elsewhere, so we should not necessarily expect a rapid takeover by BQ.1* and XBB*.

Note that Nextclade calls some of the Singapore sequences as BA.5.2.1 due to what looks like a sequencing artefact at the deletion in the N protein.

For some bizarre reason Usher is placing these sequences on a very long branch in BA.2 separate from BA.5, along with lots more BF.7 sequences. @AngieHinrichs please could you take a look?

<img width="736" alt="China_BF7" src="https://user-images.githubusercontent.com/42699509/209494779-7e1238f0-f88a-44a0-95e9-84c24c1d6ca6.png">

[https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_ad19_908010.json?branchLabel=Spike%20mutations&c=gt-S_1243&label=id:node_5329873](https://nextstrain.org/fetch/github.com/silcn/subtreeAuspice1/raw/main/auspice/subtreeAuspice1_genome_ad19_908010.json?branchLabel=Spike%20mutations&c=gt-S_1243&label=id:node_5329873)

[https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+%28G14181C+%7C+C27532T%29+%26+%5B2-of%3A+G1085T%2C+G25290T%2C+C29632T%5D&](https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?variantQuery=nextcladePangoLineage%3ABA.5.2.1*+%26+%28G14181C+%7C+C27532T%29+%26+%5B2-of%3A+G1085T%2C+G25290T%2C+C29632T%5D&)

<details><summary>EPI_ISLs</summary>

EPI_ISL_16092938
EPI_ISL_16181551
EPI_ISL_16181571
EPI_ISL_16181578
EPI_ISL_16259482
EPI_ISL_16259486
EPI_ISL_16259495
EPI_ISL_16259497
EPI_ISL_16274002
EPI_ISL_16275312
EPI_ISL_16277965
EPI_ISL_16277966
EPI_ISL_16277967
EPI_ISL_16277968
EPI_ISL_16277969
EPI_ISL_16277970
EPI_ISL_16277971
EPI_ISL_16277972
EPI_ISL_16277973
EPI_ISL_16277974
EPI_ISL_16277975
EPI_ISL_16277976
EPI_ISL_16277977
EPI_ISL_16277978
EPI_ISL_16277982
</details>

**Comment by RajLABN** [comment] 2022-12-26 04:34
Saw BF.7 + Spike C1243F in 4 sequences from Singapore (Travel history: China)

**Comment by oobb45729** [comment] 2022-12-26 05:26
BF.7+ORF7a:H47Y+ORF1b:L238F maybe should be designated first. It probably is the largest undesignated BF.7 subbranch with non-synonymous mutations right now.
https://cov-spectrum.org/explore/World/AllSamples/AllTimes/variants?variantQuery=BF.7%26ORF7a%3AH47Y%26ORF1b%3AL238F&

**Comment by oobb45729** [comment] 2022-12-26 06:32
Orf7a:H47Y is also in BF.5.

**Comment by FedeGueli** [comment] 2022-12-26 13:39
Great catch @silcn. A fast designation is deserved

**Comment by ryhisner** [comment] 2022-12-26 17:29
@silcn, it's not just this BF.7 lineage that is put in the BA.2 tree by Usher. I've noticed this happens for around half of the BF.7 sequences I upload to Usher. I'm not sure why. I wonder if the rampant misreading of N:S33F—which, as you mention, is behind the incorrect designation of a decent fraction of BF.7 as BA.5.2.1—might be behind this as well.

**Comment by oobb45729** [comment] 2022-12-27 07:15
In search of possible functions of Orf7a:H47Y, I found this article, which shows that Orf7a:F59 plays a key role in HLA-I surface downregulation.
https://www.biorxiv.org/content/10.1101/2022.05.29.493850v1.full
I checked the location of some rising Orf7a mutations recently: H47Y, S44P from BA.5.11, T61S from XAY. It turns out that they are all near F59. It's just a coincidence or not?

**Comment by FedeGueli** [comment] 2022-12-27 09:41
@oobb45729 thx very interesting. I would add that i did observe a very very rough(gisaid based) slight overrepresentation of BF.5 in samples from hospitalized people in Japan since this summer and it is still visible , i highlighted that to Sato lab and others. Wonder if if these orf7a mutations you mentioned could be linked with the findings in that paper.

**Comment by FedeGueli** [comment] 2022-12-27 20:19
67 viruses as today . 

as the other BA.5.2 + T17208C i think this should be designated as soon as possible , it has quite triplicated itself in one day.

**Comment by FedeGueli** [comment] 2022-12-28 23:31
98 viruses as today

**Comment by FedeGueli** [comment] 2022-12-29 17:36
105 sequences as today

**Comment by AngieHinrichs** [comment] 2022-12-29 18:49
> For some bizarre reason Usher is placing these sequences on a very long branch in BA.2 separate from BA.5, along with lots more BF.7 sequences. @AngieHinrichs please could you take a look?

Ugh what a mess!  Thanks @silcn, will try to fix this today.  Looks like a lot of bad luck with reversions, regular mutations and Ns going combinatoric.

**Comment by FedeGueli** [comment] 2022-12-30 15:32
123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.

**Comment by AnonymousUserUse** [comment] 2022-12-30 15:46
> 123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.

Sequences uploaded by Shanghai appears to be (at least partly) collected from imported cases. The organisation that uploads these sequences was responsible for all imported cases to Shanghai. And those sequences are not confirmed by other countries for traveler from China.

**Comment by focosi-cyber** [comment] 2022-12-30 17:11
Exactly. Readapted from https://gisaid.org/fileadmin/c/gisaid/files/pdfs/China_hCoV-19_phylo_20221230.pdf
![China variants](https://user-images.githubusercontent.com/62261114/210095842-be6491e1-dd9e-421c-85fb-279e5941e0da.jpg)

**Comment by focosi-cyber** [comment] 2022-12-30 17:15
Exactly, Rearranged from https://gisaid.org/fileadmin/c/gisaid/files/pdfs/China_hCoV-19_phylo_20221230.pdf
![China variants](https://user-images.githubusercontent.com/62261114/210096235-5c989d72-ab18-4478-9647-01b126a676c5.jpg)

**Comment by FedeGueli** [comment] 2022-12-30 20:38
i see the vast mayority of the ones uploaded today being from hospitalized cases, this points to.local circulation rather than importations.

**Comment by AnonymousUserUse** [comment] 2022-12-30 22:34
> i see the vast mayority of the ones uploaded today being from hospitalized cases, this points to.local circulation rather than importations.

All imported cases from other countries to Shanghai were hospitalized in Shanghai Public Health Clinical Center, regardless of the severity, until the beginning of December.

**Comment by FedeGueli** [comment] 2022-12-31 08:28
> > i see the vast mayority of the ones uploaded today being from hospitalized cases, this points to.local circulation rather than importations.
> 
> All imported cases from other countries to Shanghai were hospitalized in Shanghai Public Health Clinical Center, regardless of the severity, until the beginning of December.

it could be but most  samples are from second half of december. Anyway italian samples from bejing planes confirm the presence of BQ.1* lineages there together with this one and the BA.5.2+T17208C

**Comment by c19850727** [comment] 2022-12-31 15:52
> > 123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.
> 
> Sequences uploaded by Shanghai appears to be (at least partly) collected from imported cases. The organisation that uploads these sequences was responsible for all imported cases to Shanghai. And those sequences are not confirmed by other countries for traveler from China.

Here's some details regarding this batch of sequences.
![image](https://user-images.githubusercontent.com/86835836/210148789-423c81f1-d853-4b73-83f4-183292b03cd6.png)
https://doi.org/10.1007/s11684-022-0981-7

**Comment by AnonymousUserUse** [comment] 2022-12-31 16:01
> 

![image](https://user-images.githubusercontent.com/113214374/210149070-997a2d10-e9ed-4596-8cfc-e240e6af001f.png)

**Comment by AnonymousUserUse** [comment] 2022-12-31 16:01
> > > 123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.
> > 
> > 
> > Sequences uploaded by Shanghai appears to be (at least partly) collected from imported cases. The organisation that uploads these sequences was responsible for all imported cases to Shanghai. And those sequences are not confirmed by other countries for traveler from China.
> 
> Here's some details regarding this batch of sequences. ![image](https://user-images.githubusercontent.com/86835836/210148789-423c81f1-d853-4b73-83f4-183292b03cd6.png) https://doi.org/10.1007/s11684-022-0981-7

![image](https://user-images.githubusercontent.com/113214374/210149087-0c1864cf-708d-48c2-b767-319476ef1ebc.png)

**Comment by AngieHinrichs** [comment] 2022-12-31 21:51
> For some bizarre reason Usher is placing these sequences on a very long branch in BA.2 separate from BA.5, along with lots more BF.7 sequences.

This was a tough one (a few rounds of pruning and an extra-large radius in matOptimize because the branch needed to move so far), but I believe it's fixed in the 2022-12-30 tree and I'll keep an eye on it.  Thanks again @silcn and @ryhisner for pointing it out!

**Comment by ryhisner** [comment] 2023-01-01 03:06
You're a legend, @AngieHinrichs. We're all in your debt.

**Comment by FedeGueli** [comment] 2023-01-01 19:49
agree with @ryhisner

**Comment by FedeGueli** [comment] 2023-01-02 00:01
154 sequences as today, new upload from Bejing

**Comment by AnonymousUserUse** [comment] 2023-01-02 01:32
> 123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.

The correct spellings of these two cities are Beijing and Shanghai. I would appreciate it if you could spell correctly in the future.

**Comment by FedeGueli** [comment] 2023-01-02 10:55
> > 123 seqs as today. it seems dominant in Bejing while Shangai is more under a mix with variant soup wave.
> 
> The correct spellings of these two cities are Beijing and Shanghai. I would appreciate it if you could spell correctly in the future.

thx sorry typos i will call them in my mother language Italian Pechino and Shangai

**Comment by aviczhl2** [comment] 2023-01-02 12:25
https://www.medrxiv.org/content/10.1101/2022.12.27.22283698v1

This paper says variants in Hohhot were BQ.1.2, BA.5, BF.7 and BA.5.2, it is interesting that given that BF.7, BA.5.2 and BA.5 spreads all across China, there's no local BQ.1.2 sequences from China.

**Comment by FedeGueli** [comment] 2023-01-02 18:23
162 sequences as today, samples coming in from airport screening in San Francisco,CA e Lombardy,Italy

**Comment by FedeGueli** [comment] 2023-01-02 20:54
231 as now. mass upload from Pechino.

**Comment by FedeGueli** [comment] 2023-01-03 12:49
240 sequences, one from Cambodia and the rest from Italy, Lazio: interestingly they are from BAL (Broncho Alveolar lavage) , not sure of that but i dont think airport testing supports BAL as standard procedure.

**Comment by FedeGueli** [comment] 2023-01-04 07:55
272 sequences. Canada, Washington and one from Japanese airport surveillance, but travel related with **Qatar**.

**Comment by FedeGueli** [comment] 2023-01-04 18:13
285 as this evening

**Comment by FedeGueli** [comment] 2023-01-05 12:51
287. 
2 samples from Hunan

**Comment by FedeGueli** [comment] 2023-01-06 12:47
292 samples now coming from India, Israel and France. Just a thought about India which escaped a  BA.5 wave through today if maybe could be more likely to get a local wave pushed by imported lineages from China. cc @karyakarte maybe interested in.

**Comment by InfrPopGen** [comment] 2023-01-06 17:32
Thanks for submitting. We've added lineage BF.7.14 with 224 newly designated sequences, and 0 updated. Defining mutations G1085T (ORF1a:V274L), G25290T (S:C1243F), nt:C29632T (following C27532T (ORF7a:H47Y)).

**Closed by InfrPopGen** 2023-01-06 17:32 UTC
Labels: designated, BA.5

**Comment by jinyu-ncbi** [comment] 2023-01-06 19:48
We (NCBI) got 65 sequences from China this week, 54 of which are BF.7.14 sequences. In addition to ORF1a:V274L and C29632T, these sequences also have a 6-nt deletion TGGAGAACGC28360T, translating to N:GERS30S. Note that this is different from the deletion found in B.1.1.519, which is GAGAACGCAG28362G, translating to N:GERS30G. Using B.1.1.529 as the reference, it is a single-nucleotide mutation A28361G, translating to N:G30S.

10 of the 65 sequences to the helicase:T127N branch of lineage BA.5.2. These sequence have 5 extra mutations: N:Q241K and 4 synonymous mutations C2710T, C8626T, C11824T and T17280C.
