### ISSUE TITLE
KD.5 Retraction Request

### ISSUE THREAD

**Issue by Over-There-Is** [cov-lineages/pango-designation#2405] opened 2023-12-07 20:39 UTC
22289-22294 sites of XBC is deleted, and it causes S:del243-244. As both S:242 and S:244 are Leucine residue, it is always also described as S:del242-243.
Sometimes, TT on 22287-22288 sites is duplicated and causes artefactual frameshift. These sequences are analyzed as having del22286-22289 and A22294T, and even got analyzed as "S:L244F" further.
In UShER, 55 sequences are assigned as KD.5. Some of its subbranches share mutations with other branches. The largest subbranch with 30 sequences has 2 private synonymous mutations: C4456T, A10621G, I do not consider this subbranch worth designated.
![image](https://github.com/cov-lineages/pango-designation/assets/38100637/26cc3eed-8de0-4843-a298-a649ea706fa6)
![2023-12-06 (7)](https://github.com/cov-lineages/pango-designation/assets/38100637/a352652d-ec24-4237-bec8-f40b29894a56)
![2023-12-06 (9)](https://github.com/cov-lineages/pango-designation/assets/38100637/6cb53387-d53a-4020-9a83-99bc048f36a0)
![2023-12-08 (4)](https://github.com/cov-lineages/pango-designation/assets/38100637/7fac5780-17f6-4b80-9eed-ce579b7979be)

**Comment by aviczhl2** [comment] 2023-12-08 03:07
@AngieHinrichs  suggest to put a branch-specific mask for XBC.1.3.1

**Comment by Over-There-Is** [comment] 2023-12-08 05:44
and the note text of XBC.1.1.2 should also be modified.

**Comment by Over-There-Is** [comment] 2023-12-17 10:06
@corneliusroemer

**Comment by corneliusroemer** [comment] 2023-12-17 10:54
Thanks for the nice analysis of why we see those 244 artefacts!

I already wondered why KD.5 doesn't have any defining mutations on my Nextclade reference tree, looks like this was a bad designation then. Will have a look!

<img width="842" alt="image" src="https://github.com/cov-lineages/pango-designation/assets/25161793/9ae89826-2efc-482c-9369-8b7c2b74bdd9">

**Comment by AngieHinrichs** [comment] 2023-12-21 23:01
Thanks @Over-There-Is.  I will mask the deleted range in all of XBC.  (starting with 2023-12-22 build)

**Comment by AngieHinrichs** [comment] 2023-12-23 00:30
Confirmed the UShER tree no longer has a KD.5 branch as of 2023-12-22, due to masking the deleted range in XBC.  I agree with @Over-There-Is's comment above that the description of XBC.1.1.2 in lineage_notes.txt should be updated to no longer include S:L244F because that was an artefact.

**Comment by Memorablea** [comment] 2023-12-24 05:45
> Confirmed the UShER tree no longer has a KD.5 branch as of 2023-12-22

![image](https://github.com/cov-lineages/pango-designation/assets/125779492/d0d67da8-2a28-4499-ab2d-d4a6949875ef)
The file has not been updated.

**Comment by AngieHinrichs** [comment] 2024-01-08 17:20
@corneliusroemer I am going to do a PR to remove KD.5 from lineages.csv and lineage_notes.txt unless you object soon.  🙂

**Comment by corneliusroemer** [comment] 2024-01-08 18:02
Fixed in #2443

**Closed by corneliusroemer** 2024-01-08 18:02 UTC
