### ISSUE TITLE
Proposal of Two Potential New Lineages

### ISSUE THREAD

**Issue by c19850727** [cov-lineages/pango-designation#150] opened 2021-07-18 16:51 UTC
### Proposed Lineage 1:
Sublineage of C.11 (6 out of 9 samples are currently classified as C.11, and other 3 as B.1.1.1)
Earliest sequence: 2021/3/20 (Estonia, with a travel history to Egypt)
Most recent sequence: 2021/7/4 (Italy)
Spike mutations: P9L, W64R, DEL138/144, E484K, D614G, D796Y
Countries: Estonia, Germany, France, Italy, Lithuania, Portugal, Switzerland, Ireland, Netherlands, UK, US
Genomes:
hCoV-19/Estonia/Cov10559/2021 (Estonia, ex Egypt)
hCoV-19/Estonia/Cov10900/2021 (Estonia, ex Egypt)
hCoV-19/Italy/ABR-ET42/2021 (Italy)
hCoV-19/Slovakia/UVZ_PL14_B12_9151/2021 (Slovakia)
hCoV-19/Lithuania/LTU000_BM_28BM/2021 (Lithuania)
hCoV-19/Portugal/PT7247/2021 (Portugal)
hCoV-19/Italy/LOM-Policlinico_Milano_18803787/2021 (Italy)
hCoV-19/Germany/RP-RKI-I-152756/2021 (Germany)
hCoV-19/Italy/SIC_CQRC_21057055/2021 (Italy)

### Proposed Lineage 2:
Sublineage of C.1
Earliest sequence: 2021/6/16 (South Africa)
Most recent sequence: 2021/6/27 (UK)
Spike mutations: P9L, C136F, R190S, D215G, DEL242/243, Y449H, E484K, N501Y, D614G, H655Y, N679K
Countries: South Africa, UK, Switzerland, China
Genomes:
hCoV-19/SouthAfrica/NICD-N9382/2021 (South Africa)
hCoV-19/SouthAfrica/KRISP-K018657/2021 (South Africa)
hCoV-19/SouthAfrica/NICD-N9628/2021 (South Africa)
hCoV-19/SouthAfrica/VIDA-KRISP-K018963/2021 (South Africa)
hCoV-19/England/MILK-17E1CDA/2021 (UK)

**Comment by FedeGueli** [comment] 2021-07-19 18:49
The proposed lineage 2 is a duplicate of #139

**Comment by c19850727** [comment] 2021-07-20 03:12
> The proposed lineage 2 is a duplicate of #139

Yes it is. 
Thanks!

**Comment by thomasppeacock** [comment] 2021-07-23 17:54
Some further genomes that appear to cluster with proposed lineage 1 (73 total)

[new lineage one.csv.txt](https://github.com/cov-lineages/pango-designation/files/6870437/new.lineage.one.csv.txt)

**Comment by c19850727** [comment] 2021-07-24 03:19
> Some further genomes that appear to cluster with proposed lineage 1 (73 total)
> 
> [new lineage one.csv.txt](https://github.com/cov-lineages/pango-designation/files/6870437/new.lineage.one.csv.txt)

Thanks!

**Comment by chrisruis** [comment] 2021-07-28 10:42
Thanks @c19850727 and @thomasppeacock. It looks like these sequences descend from B.1.1.1 rather than C.11 in the latest UShER tree:
https://nextstrain.org/fetch/hgwdev.gi.ucsc.edu/trash/ct/subtreeAuspice1_hgwdev_18ead_11b100.json?c=pango_lineage

C.11 is defined by C27804T which these sequences don't have, further supporting them descending from B.1.1.1 rather than C.11. We've therefore added this as C.38 in [v1.2.46](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.46) with 101 new sequence designations

**Closed by chrisruis** 2021-07-28 10:42 UTC
