### ISSUE TITLE
Emerging B.1.X variant lineage in Europe and Africa with conserved Spike mutations: P9L, E96Q, R346S, Y449N, P681H and T859N

### ISSUE THREAD

**Issue by thomasppeacock** [cov-lineages/pango-designation#297] opened 2021-10-28 14:22 UTC
**New proposed lineage
By Tom Peacock** (also identified independently by @c19850727)

**Description**
**Sub-lineage of:** B.1
**Earliest Sequence:** 2021-09-28
**Latest Sequence:** 2021-10-18

**Countries circulating:** UK (2 genomes), Switzerland (1 genome), France (1 genome), Republic of Congo (1 genome)

**Description:**
Conserved Spike mutations - P9L, E96Q, Δ136-144*, R190S*, I210T*, R346S, N394S, Y449N, F490R*, N501Y*, D614G, P681H, T859N, D936H* (*seen conserved in all sequenced except French sequence)

Conserved non-Spike mutations - NSP2 – P129L, E272G*; NSP3 – L1301F*, A1537A*; NSP4 – S386F* R401H*, T492I; NSP6 – V149A*; NSP12 – P323l; ORF3a – T32I*, Q57H*; M – I82T; ORF8 – Q27*STOP; N- D22Y, T205I, E378Q (*found in all but one sequence)

Although there are currently only 5 sequences the i) extremely short period of time between first and most recent case, ii) (presumed) repeated import into European countries, iii) presence in Central Africa where surveillence is otherwise quite low, and iv) appearance despite Delta wiping out all other variant lineages globally makes me think this was worth flagging even with this few sequences. 

It appears likely there is a lot more of this around than surveillence would otherwise imply and it would be useful to have a pango lineage assigned to allow rapid identification in future surveillence.

**Genomes:**
EPI_ISL_5481688
EPI_ISL_5619557
EPI_ISL_5592661
EPI_ISL_5531392
EPI_ISL_5588295 (this French sequence appears like it might have a lot of WT backcalling, rather than being a true ancestral sequence)

**Evidence:** 
![image](https://user-images.githubusercontent.com/79373149/139275325-08e85b89-7977-43ce-ae85-ac3a5adf4244.png)

https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_1a121_aa3ca0.json?c=pango_lineage

**Proposed lineage name:** B.1.X

**Comment by thomasppeacock** [comment] 2021-11-01 18:25
New sequence from Italy (ID'd by @c19850727):

EPI_ISL_5796708

**Comment by thomasppeacock** [comment] 2021-11-05 12:03
Further sequences from France (currently called as B.1.628 or 'none'):
EPI_ISL_5926666
EPI_ISL_5914084

There are now sequences from the North West, Centre and South East of France indicating there might be quite widespread dispersal through the country (or maybe multiple import clusters)

**Comment by georgimarinov** [comment] 2021-11-08 01:16
This has all the signs of the dreaded complete or near-complete escape variant -- R346, N394, Y449, F490, plus lots of bad NTD mutations, i.e. I would be very highly surprised if this shows less neutralization reduction than the current champion C.1.2.

It really needs to be designated ASAP so that it is on people's minds and it is properly monitored, even if it eventually goes nowhere rather than being a January 2020-type situation.

**Comment by AngieHinrichs** [comment] 2021-11-08 23:33
@russcd @yatisht This is a tough one for the UCSC/UShER tree because it is so far diverged from any other sequences that it can't be placed with confidence.  Sequences in this cluster are rejected from the daily tree update for two reasons:
1. too many equally parsimonious placements in the tree (>5 rejected; most of these have at least 6)
2. more than 20 mutations on a branch (usually this is caused by sequences having lots of errors, but these sequences seem consistent with each other, just really diverged since any common ancestor was sequenced)

It does seem worth labeling and tracking this.  Sorry that the sequences won't have a place in the UCSC/UShER tree unless we figure out how to exempt them from our filters.  I am doing a special run of usher in --multiple mode to see the 6 equally parsimonious possible placements to see if any of them look any better or worse than the others.

**Comment by thomasppeacock** [comment] 2021-11-09 10:52
thanks @AngieHinrichs thats very interesting!

**Further 7 sequences just uploaded from Congo:**
EPI_ISL_6077271
EPI_ISL_6077280
EPI_ISL_6077285
EPI_ISL_6077286
EPI_ISL_6077287
EPI_ISL_6077288
EPI_ISL_6077289

**latest Usher tree:**
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/subtreeAuspice1_genome_935d_a528a0.json

Interestingly the two Paris region samples are outliers - initially thought they might be poor seq/WT calling but starting to wonder whether they might genuinely represent large diversity within this lineage...

**Comment by thomasppeacock** [comment] 2021-11-09 16:59
**First USA sequence (California):**
EPI_ISL_6095997

**Comment by russcd** [comment] 2021-11-09 17:11
I'd suggest we add this clade as an exception to standard QC. Then, if/when additional samples from this lineage are added, they will presumably have on obvious correct placement relative to each other. The exact placement of the long branch on the main tree is pretty inconsequential given how divergent this clade is, but we should have this in our tree. 

@AngieHinrichs what do you think?

**Comment by yatisht** [comment] 2021-11-09 17:56
Yeah, does make sense to make an exception in this case.

**Comment by AngieHinrichs** [comment] 2021-11-10 03:53
Thanks @russcd for pointing out that if all sequences are added without the branch length filter, there is enough breaking up of the long branch for the sequences to be kept if the filter is applied only afterwards, and not all of the sequences have too many equally parsimonious placements.  I will try to work the sequences into today's tree, and move the long-branch filter out of usher into a post-processing step.

**Comment by vthibault35** [comment] 2021-11-10 17:14
For your information, it seems that the cluster from the west of France (our sequences from Rennes Hospital) could geographicaly be linked to a traveler coming from Congo. It would be interesting to look whether there is a link with Africa for the other described strains from diverse regions of the world. Unless the virus is under a strong pressure, I have difficulties to understand how this very peculiar strain appeared in different countries. Any information on possible travels or links with Africa would be very interesting.

**Comment by chrisruis** [comment] 2021-11-10 17:55
Thanks @thomasppeacock We've added this as B.1.640 in [v1.2.94](https://github.com/cov-lineages/pango-designation/releases/tag/v1.2.94) and included all 22 of the sequences from your comments above with <5% ambiguity.

I'll close this issue now so we know it's been designated but if there's any more discussion about these sequences, travel history, etc, please do keep that going below

**Closed by chrisruis** 2021-11-10 17:55 UTC
Labels: proposed

**Comment by shay671** [comment] 2021-11-10 21:54
I found 25 samples with the 3 S mutations :E96Q,P9L,N394S

Here is it's USHER build :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1a69_c10090.json?label=nuc%20mutations:C10029T,G23012A,A23063T,C23604A,A26492T,C27925A,C28005T,C28093T,C28887T


![640](https://user-images.githubusercontent.com/80166370/141198931-4df97dd5-e95f-4e35-b749-4e360ca2dc4e.jpg)


A - France 
B - UK, Swizerland, Scotland, Italy, France, USA & Congo 
C - Congo 
D- Congo 
E - France 

E (EPI_ISL_5926666) looks a bit outlier. If i take the consensus mutations of groups A-D (34) it has only 19 of those. 

Another sample , EPI_ISL_5588295, Appeared in Delta (21J)
But it only has 16 out of the 30 mutations i found in the consensus of 21j and only 13 mutations out of the 34 mutations that are in consensus in the 4 groups of B.1.640 i mentioned above.  
Maybe some sequence contamination? (the shared mutations with 21J and B.1.640 are in a mixture along the genome).

**Comment by LVerdurme** [comment] 2021-11-12 11:30
Dear all,
This one EPI_ISL_5588295 comes from my lab and appears to be the first case of the cluster in a school in Brittany seen by @vthibault35. It's a traveller back from Congo on 16th october who currently lives in Nantes.
We are going to control this sequence to make things clearer.

**Comment by shay671** [comment] 2021-11-12 11:55
Hi @LVerdurme 

This data is very important.
The sample you gave here actually does not cluster with the other in this lineage but rather seems to cluster with Delta (21J main cluster). It has actually more mutations of that Delta clade than the consensus of the other in B.1.640. It seems less likely to be a cause of recombination as the Delta mutations in this sequence are spread along the genome.
Here is the USHER build for that :
https://nextstrain.org/fetch/genome.ucsc.edu/trash/ct/singleSubtreeAuspice_genome_1fecb_e53fe0.json

**Comment by bettekorber** [comment] 2021-11-19 20:42
Hi, I'm puzzled as some of the sequences in this discussion seem to have been redesignated, from B.1 to B.1.576 (e.g.  EPI_ISL_6095997 and EPI_ISL_5655478) in the Pango lineage notes in GISAID. I was expecting to see these changing to B.1.640. B.1.576 is a old lineage without sporadic Spike changes. Is this as intended?

**Comment by erikalmecdc** [comment] 2021-11-23 13:59
It looks like those are spurious assignments, caused by B.1.640 not yet being implemented in GISAID. Out of these ones we think are B.1.640 about half are now B.1 and half B.1.576 in GISAID.

**Comment by FedeGueli** [comment] 2021-12-25 21:38
![Screenshot_2021-12-24-16-16-21-945_com android chrome](https://user-images.githubusercontent.com/87669813/147393961-36ea774e-0c5c-4522-bb39-c4aa052417cc.jpg)
This interesting plot by V.Colizza et al shows the trend of this variant in France in comparison to Omicron.
Put this here if by chance in future could be of some interest.
