### ISSUE TITLE
Potential New Lineage with Spike G142D, K182R, L452R, T478K, P681H, D796Y, C1235F.

### ISSUE THREAD

**Issue by shay671** [cov-lineages/pango-designation#144] opened 2021-07-14 09:13 UTC
Description
Sub-lineage of: B.1
Clade: 20C
Countries: France,UK, Guinea,Spain, Germany,Angola, Italy,
Earliest sequence: 2021-02-23
Most recent sequence: 2021-06-23

49 sequences 

Defining mutations in Spike:
S:G142D
S:K182R
S:L452R
S:T478K
S:P681H
S:D796Y
S:C1235F
(Additional to that there are 13 other non synonymous mutations, 4 synonymous and 2 in extragenic regions). 

List of GISAID refence to the sequences are in the first comment

**Comment by shay671** [comment] 2021-07-14 09:14
[GISAID list.xlsx](https://github.com/cov-lineages/pango-designation/files/6814928/GISAID.list.xlsx)

**Comment by babarlelephant** [comment] 2021-07-15 13:09
Hi, Usher tree there https://nextstrain.org/community/babarlelephant/cov/subtreeAuspice1/genome/5556b/acca20 (the orange lineage) obtained from entering EPI_ISL_2723579 and 1000 sequences context in https://genome.ucsc.edu/cgi-bin/hgPhyloPlace

**Comment by thomasppeacock** [comment] 2021-07-16 10:17
I think this might be a duplicate of issue #132 which got assigned as B.1.629 a couple of weeks back (https://github.com/cov-lineages/pango-designation/issues/132)

**Comment by shay671** [comment] 2021-07-16 10:23
After comparing the mutations consensus i think that you are completely right.

**Comment by AngieHinrichs** [comment] 2021-07-16 18:40
Thank you for spotting that @thomasppeacock.

**Closed by AngieHinrichs** 2021-07-16 18:40 UTC
